### ISSUE TITLE
pdb_in not declared

### ISSUE THREAD

**Issue by almeida85** [samuelmurail/gromacs_py#17]
Hi,

I started playing with `gromacs_py` and got the following error:

```
>>> md_sys.prepare_top(out_folder=os.path.join(DATA_OUT, 'prot_top'), vsite=vsite, ff='amber99sb-ildn')
pdb2pqr_cli --ff AMBER --ffout AMBER --chain --ph-calc-method=propka --with-ph=7.00 tmp_pdb2pqr.pdb 00_1Y0M.pqr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/almeida/.local/lib/python3.8/site-packages/gromacs_py/gmx.py", line 1997, in prepare_top
    coor_in = pdb_manip.Coor(pdb_in="00_" + name + ".pqr",
TypeError: __init__() got an unexpected keyword argument 'pdb_in'
```
`pdb_in` is not declared anywhere.

Any thought?

Thanks in advance,
-Yasser

**Comment by samuelmurail** [comment]
Dear Yasser,

It is a bit hard, to answer your question. I suspect you are using an old version of gromacs_py.
Could you let me know which version of gromacs_py you are using, and by wich way you install gromacs_py (conda, pip, github).

Cheers,
Samuel

**Comment by almeida85** [comment]
Dear Samuel,

I installed gromacs_py directly with `pip3 install gromacs_py`.

Best,
Yasser

**Comment by samuelmurail** [comment]
Dear Yasser,

My bad, I wasn't specifying the dependencies version.
The last versions of `pdb_manip_py` have change, so you should get an older version of `pdb_manip_py`:

```bash
pip install pdb_manip_py==1.2.4
# If you want to use the notebook example, install also:
pip install tqdm simpletraj nglview
```

Let me know, if it has solve your issue.

I will release a new pypi version soon with the correct dependencies.

Cheers,
Samuel

**Comment by almeida85** [comment]
Solved! ;)

Thanks
