### ISSUE TITLE
Unknown OpenCL error: -9999

### ISSUE THREAD

**Issue by Datadriven1** [samuelmurail/gromacs_py#22]
I got error while running "md_sys.em_2_steps(out_folder=em_folder,
                  no_constr_nsteps=em_step_number,
                  constr_nsteps=em_step_number,
                  posres="",
                  create_box_flag=False,
                  emtol=0.1, nstxout=100)"

Error is "Internal error (bug):
Failed to compile NBNXN kernels for GPU #NVIDIA A100-SXM4-40GB
  Could not build OpenCL program, error was Unknown OpenCL error: -9999

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors"

I am using Nvidia DGX A100 GPU.

**Comment by hozeren** [comment]
It seems GPU+GROMACS problem rather than gromacs_py. 

Which version of GROMACS do you use? Is it working without gromacs_py? You can take a look this thread as well;
https://mailman-1.sys.kth.se/pipermail/gromacs.org_gmx-users/2019-February/124394.html

**Comment by samuelmurail** [comment]
Yes indeed, the issue is related to gromacs installation.

I presume that you installed gromacs throught the conda environment.
I would suggest to uninstall gromacs throught conda and reinstall gromacs with CUDA support, see:
https://manual.gromacs.org/documentation/current/install-guide/index.html
using this option :
```
cmake .. -DGMX_GPU=CUDA ...
```

Let me know if it works.

**Comment by Datadriven1** [comment]
I am using gromacs through python script available at "https://gromacs-py.readthedocs.io/en/latest/installation.html#". clone gromacs_py repo as requested and installed according to instruction. After multiple try, able to run gromacs using python script but it used DGX CPU not GPU. Please advise if there is any option to change CUDA instead of OpenCL.

**Comment by hozeren** [comment]
As @samuelmurail explained and it is also mention in README.rst, you should uninstall gromacs that you installed with conda environment and reinstall again, I suppose there is no other way around it for now.

```bash
conda remove gromacs #not sure but should be something like this.
```
then install officially following this and add CUDA support: https://manual.gromacs.org/documentation/current/install-guide/index.html
```bash
cmake ... -DGMX_GPU=CUDA
```

It was already explained in the previous comment.

**Comment by Datadriven1** [comment]
Thanks for your support.
