### ISSUE TITLE
 pytest progress show ValueError

### ISSUE THREAD

**Issue by chenbq18** [samuelmurail/gromacs_py#23]
ERROR gromacs_py/test/test_FreeEner.py - ValueError: could not convert string to float: '5.1.5'
ERROR gromacs_py/test/test_FreeEner.py - ValueError: could not convert string to float: '5.1.5'
ERROR gromacs_py/test/test_GmxSys.py - ValueError: could not convert string to float: '5.1.5'
ERROR gromacs_py/test/test_GmxSys.py - ValueError: could not convert string to float: '5.1.5'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================== 4 errors in 26.01s ===================================================================

**Comment by samuelmurail** [comment]
I did a fix for people using gromacs 5.1.5. There is still one test failling, but it is mainly OK.
However, I don't recommand using such old version of gromacs.
